/**
 * maintenance-auto-scheduler
 *
 * Scans every organization's active maintenance_schedules and auto-creates a
 * work_orders row when:
 *   - schedule is "due" by date / odometer / hours, OR
 *   - schedule is within its reminder window (reminder_days_before / reminder_km_before), OR
 *   - vehicle MTBF (mean time between failures) for the same service_type is
 *     <= the rolling MTBF threshold stored on the schedule (interval_type='mtbf')
 *
 * Per vehicle-class overrides
 *   `maintenance_class_overrides` rows let ops tune the MTBF threshold and
 *   reminder windows by vehicle_type (+ optional service_type). A row matching
 *   (organization_id, vehicle_type, service_type) wins over a wildcard row
 *   (service_type IS NULL); both win over the schedule's own values.
 *
 * Idempotent: if an OPEN (pending|in_progress|approved) work order already
 * exists for the same maintenance_schedule_id, a duplicate is NOT created.
 *
 * Triggered by:
 *   - pg_cron (hourly) via net.http_post
 *   - "Run Scheduler Now" admin button on /maintenance
 *   - "Dry-Run Preview" dialog on /maintenance (body.dry_run = true)
 *
 * Body (optional)
 *   { "organization_id": "<uuid>" }   -- limit to one org for manual runs
 *   { "dry_run": true }                -- compute candidates but skip inserts
 */
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

type Schedule = {
  id: string;
  organization_id: string;
  vehicle_id: string;
  service_type: string;
  interval_type: "date" | "odometer" | "hours" | "mtbf" | string;
  interval_value: number;
  last_service_date: string | null;
  last_service_odometer: number | null;
  last_service_hours: number | null;
  next_due_date: string | null;
  next_due_odometer: number | null;
  next_due_hours: number | null;
  reminder_days_before: number | null;
  reminder_km_before: number | null;
  priority: string | null;
};

type Vehicle = {
  id: string;
  license_plate: string | null;
  vehicle_type: string | null;
  current_odometer: number | null;
  engine_hours: number | null;
};

type ClassOverride = {
  organization_id: string;
  vehicle_type: string;
  service_type: string | null;
  mtbf_days: number | null;
  reminder_days_before: number | null;
  reminder_km_before: number | null;
  reminder_hours_before: number | null;
  priority: string | null;
};

interface DecisionContext {
  schedule: Schedule;
  vehicle: Vehicle | null;
  /** Why the scheduler chose to create a WO (for the "remark" field). */
  reason: string;
  /** ISO date string for scheduled_date on the new WO. */
  scheduledDate: string;
  /** Effective priority after class override. */
  priority: string;
  /** Override row that influenced the decision, for transparency in dry-runs. */
  override: ClassOverride | null;
}

/**
 * Resolve the best class override for a given (org, vehicle_type, service_type).
 * Specific service_type wins over wildcard (NULL).
 */
function resolveOverride(
  overrides: ClassOverride[],
  orgId: string,
  vehicleType: string | null,
  serviceType: string,
): ClassOverride | null {
  if (!vehicleType) return null;
  const candidates = overrides.filter(
    (o) => o.organization_id === orgId && o.vehicle_type === vehicleType,
  );
  return (
    candidates.find((o) => o.service_type === serviceType) ??
    candidates.find((o) => o.service_type === null) ??
    null
  );
}

/**
 * Decide whether a given schedule needs a new work order generated *now*.
 * Returns null if no action is required.
 */
function evaluateSchedule(
  schedule: Schedule,
  vehicle: Vehicle | null,
  mtbfDays: number | null,
  override: ClassOverride | null,
): DecisionContext | null {
  const now = new Date();
  const nowISO = now.toISOString().slice(0, 10);
  const priority = override?.priority || schedule.priority || "medium";

  // 1. Date-based schedules ----------------------------------------------------
  if (schedule.interval_type === "date" && schedule.next_due_date) {
    const due = new Date(schedule.next_due_date);
    const diffDays = Math.round(
      (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24),
    );
    const reminderDays =
      override?.reminder_days_before ?? schedule.reminder_days_before ?? 7;
    if (diffDays <= reminderDays) {
      return {
        schedule,
        vehicle,
        priority,
        override,
        scheduledDate: due < now ? nowISO : schedule.next_due_date.slice(0, 10),
        reason:
          diffDays < 0
            ? `Overdue by ${Math.abs(diffDays)} day(s) — auto-generated by scheduler`
            : `Due in ${diffDays} day(s) — within ${reminderDays}-day reminder window${override ? " (class override)" : ""}`,
      };
    }
  }

  // 2. Odometer-based schedules -----------------------------------------------
  if (
    schedule.interval_type === "odometer" &&
    schedule.next_due_odometer != null &&
    vehicle?.current_odometer != null
  ) {
    const remaining = schedule.next_due_odometer - vehicle.current_odometer;
    const reminderKm =
      override?.reminder_km_before ?? schedule.reminder_km_before ?? 500;
    if (remaining <= reminderKm) {
      return {
        schedule,
        vehicle,
        priority,
        override,
        scheduledDate: nowISO,
        reason:
          remaining < 0
            ? `Overdue by ${Math.abs(remaining).toFixed(0)} km`
            : `Due in ${remaining.toFixed(0)} km (within ${reminderKm} km reminder${override ? ", class override" : ""})`,
      };
    }
  }

  // 3. Engine-hour schedules --------------------------------------------------
  if (
    schedule.interval_type === "hours" &&
    schedule.next_due_hours != null &&
    vehicle?.engine_hours != null
  ) {
    const remainingHrs = schedule.next_due_hours - vehicle.engine_hours;
    const reminderHrs = override?.reminder_hours_before ?? 25;
    if (remainingHrs <= reminderHrs) {
      return {
        schedule,
        vehicle,
        priority,
        override,
        scheduledDate: nowISO,
        reason:
          remainingHrs < 0
            ? `Overdue by ${Math.abs(remainingHrs).toFixed(0)} engine hours`
            : `Due in ${remainingHrs.toFixed(0)} engine hours (within ${reminderHrs}h${override ? ", class override" : ""})`,
      };
    }
  }

  // 4. MTBF-based schedules ---------------------------------------------------
  if (schedule.interval_type === "mtbf" && mtbfDays != null && mtbfDays > 0) {
    const threshold = override?.mtbf_days ?? schedule.interval_value;
    if (mtbfDays < threshold) {
      return {
        schedule,
        vehicle,
        priority,
        override,
        scheduledDate: nowISO,
        reason: `MTBF dropped to ${mtbfDays.toFixed(1)} days (threshold ${threshold} days${override ? `, class override for ${vehicle?.vehicle_type}` : ""}) — preventive WO`,
      };
    }
  }

  return null;
}

/**
 * Compute mean time between failures (in days) for a vehicle + service_type
 * over its last N completed work orders. Returns null if fewer than 2 events.
 */
async function computeMtbfDays(
  supabase: any,
  vehicleId: string,
  serviceType: string,
): Promise<number | null> {
  const { data, error } = await supabase
    .from("work_orders")
    .select("completed_date")
    .eq("vehicle_id", vehicleId)
    .eq("service_category", serviceType)
    .eq("status", "completed")
    .not("completed_date", "is", null)
    .order("completed_date", { ascending: false })
    .limit(6);
  if (error || !data || data.length < 2) return null;
  const dates = data
    .map((d: any) => new Date(d.completed_date).getTime())
    .sort((a: number, b: number) => a - b);
  const intervals: number[] = [];
  for (let i = 1; i < dates.length; i++) {
    intervals.push((dates[i] - dates[i - 1]) / (1000 * 60 * 60 * 24));
  }
  return intervals.reduce((a, b) => a + b, 0) / intervals.length;
}

async function generateWorkOrderNumber(
  supabase: any,
  organizationId: string,
): Promise<string> {
  const prefix = `WO-AUTO-${new Date().getFullYear()}`;
  const { count } = await supabase
    .from("work_orders")
    .select("id", { count: "exact", head: true })
    .eq("organization_id", organizationId)
    .like("work_order_number", `${prefix}%`);
  const seq = String((count ?? 0) + 1).padStart(5, "0");
  return `${prefix}-${seq}`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
  const body = req.method === "POST" ? await req.json().catch(() => ({})) : {};
  const orgFilter: string | undefined = body.organization_id;
  const dryRun: boolean = Boolean(body.dry_run);

  // Pull active schedules (optionally scoped to one org)
  let q = supabase
    .from("maintenance_schedules")
    .select("*")
    .eq("is_active", true);
  if (orgFilter) q = q.eq("organization_id", orgFilter);
  const { data: schedules, error: sErr } = await q;
  if (sErr) {
    return new Response(JSON.stringify({ error: sErr.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  // Bulk-load vehicles for the schedules in scope
  const vehicleIds = [...new Set((schedules ?? []).map((s) => s.vehicle_id))];
  const { data: vehicles } = await supabase
    .from("vehicles")
    .select("id, license_plate, vehicle_type, current_odometer, engine_hours")
    .in("id", vehicleIds);
  const vmap = new Map((vehicles ?? []).map((v: any) => [v.id, v as Vehicle]));

  // Bulk-load class overrides for orgs in scope
  const orgIds = [...new Set((schedules ?? []).map((s) => s.organization_id))];
  let oq = supabase
    .from("maintenance_class_overrides")
    .select(
      "organization_id, vehicle_type, service_type, mtbf_days, reminder_days_before, reminder_km_before, reminder_hours_before, priority",
    )
    .eq("is_active", true);
  if (orgIds.length) oq = oq.in("organization_id", orgIds);
  const { data: overrideRows } = await oq;
  const overrides = (overrideRows ?? []) as ClassOverride[];

  // Find schedules that already have an open WO so we can skip them
  const scheduleIds = (schedules ?? []).map((s) => s.id);
  const { data: openWos } = await supabase
    .from("work_orders")
    .select("maintenance_schedule_id")
    .in("maintenance_schedule_id", scheduleIds)
    .in("status", ["pending", "in_progress", "approved"]);
  const occupied = new Set(
    (openWos ?? []).map((w: any) => w.maintenance_schedule_id),
  );

  const created: Array<{
    schedule_id: string;
    vehicle_id: string;
    license_plate: string | null;
    vehicle_type: string | null;
    service_type: string;
    work_order_number: string;
    priority: string;
    scheduled_date: string;
    reason: string;
    override_applied: boolean;
  }> = [];
  const skipped: Array<{ schedule_id: string; reason: string }> = [];

  for (const s of (schedules ?? []) as Schedule[]) {
    if (occupied.has(s.id)) {
      skipped.push({ schedule_id: s.id, reason: "open WO exists" });
      continue;
    }
    const v = vmap.get(s.vehicle_id) ?? null;
    const override = resolveOverride(
      overrides,
      s.organization_id,
      v?.vehicle_type ?? null,
      s.service_type,
    );
    const mtbf =
      s.interval_type === "mtbf"
        ? await computeMtbfDays(supabase, s.vehicle_id, s.service_type)
        : null;
    const decision = evaluateSchedule(s, v, mtbf, override);
    if (!decision) {
      skipped.push({ schedule_id: s.id, reason: "not due" });
      continue;
    }

    if (dryRun) {
      created.push({
        schedule_id: s.id,
        vehicle_id: s.vehicle_id,
        license_plate: v?.license_plate ?? null,
        vehicle_type: v?.vehicle_type ?? null,
        service_type: s.service_type,
        work_order_number: "(dry-run)",
        priority: decision.priority,
        scheduled_date: decision.scheduledDate,
        reason: decision.reason,
        override_applied: !!override,
      });
      continue;
    }

    const woNumber = await generateWorkOrderNumber(supabase, s.organization_id);
    const { error: insErr } = await supabase.from("work_orders").insert({
      organization_id: s.organization_id,
      vehicle_id: s.vehicle_id,
      maintenance_schedule_id: s.id,
      work_order_number: woNumber,
      work_type: "preventive",
      service_category: s.service_type,
      service_description: `Auto-generated: ${s.service_type}`,
      priority: decision.priority,
      status: "pending",
      approval_status: "pending",
      scheduled_date: decision.scheduledDate,
      odometer_at_service: v?.current_odometer ?? null,
      remark: decision.reason,
      created_by_name: "Auto-Scheduler",
    });
    if (insErr) {
      skipped.push({
        schedule_id: s.id,
        reason: `insert failed: ${insErr.message}`,
      });
      continue;
    }
    created.push({
      schedule_id: s.id,
      vehicle_id: s.vehicle_id,
      license_plate: v?.license_plate ?? null,
      vehicle_type: v?.vehicle_type ?? null,
      service_type: s.service_type,
      work_order_number: woNumber,
      priority: decision.priority,
      scheduled_date: decision.scheduledDate,
      reason: decision.reason,
      override_applied: !!override,
    });
  }

  return new Response(
    JSON.stringify({
      ok: true,
      dry_run: dryRun,
      examined: schedules?.length ?? 0,
      created: created.length,
      skipped: skipped.length,
      created_items: created,
      skipped_items: skipped.slice(0, 50),
      ran_at: new Date().toISOString(),
    }),
    { headers: { ...corsHeaders, "Content-Type": "application/json" } },
  );
});
