
-- Add workflow columns to maintenance_requests
ALTER TABLE public.maintenance_requests
  ADD COLUMN IF NOT EXISTS workflow_stage text DEFAULT 'submitted',
  ADD COLUMN IF NOT EXISTS pre_inspection_done boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS pre_inspection_by text,
  ADD COLUMN IF NOT EXISTS pre_inspection_at timestamptz,
  ADD COLUMN IF NOT EXISTS pre_inspection_notes text,
  ADD COLUMN IF NOT EXISTS needs_maintenance boolean,
  ADD COLUMN IF NOT EXISTS supplier_id text,
  ADD COLUMN IF NOT EXISTS supplier_name text,
  ADD COLUMN IF NOT EXISTS vehicle_delivered_at timestamptz,
  ADD COLUMN IF NOT EXISTS vehicle_delivered_by text,
  ADD COLUMN IF NOT EXISTS variation_requested boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS variation_notes text,
  ADD COLUMN IF NOT EXISTS variation_accepted boolean,
  ADD COLUMN IF NOT EXISTS variation_accepted_by text,
  ADD COLUMN IF NOT EXISTS variation_accepted_at timestamptz,
  ADD COLUMN IF NOT EXISTS inspector_id text,
  ADD COLUMN IF NOT EXISTS inspector_assigned_at timestamptz,
  ADD COLUMN IF NOT EXISTS post_inspection_result text,
  ADD COLUMN IF NOT EXISTS post_inspection_at timestamptz,
  ADD COLUMN IF NOT EXISTS post_inspection_notes text,
  ADD COLUMN IF NOT EXISTS maintenance_accepted boolean,
  ADD COLUMN IF NOT EXISTS maintenance_accepted_at timestamptz,
  ADD COLUMN IF NOT EXISTS maintenance_accepted_by text,
  ADD COLUMN IF NOT EXISTS delivery_document_url text,
  ADD COLUMN IF NOT EXISTS delivery_checked_at timestamptz,
  ADD COLUMN IF NOT EXISTS delivery_acceptable boolean,
  ADD COLUMN IF NOT EXISTS vehicle_received_at timestamptz,
  ADD COLUMN IF NOT EXISTS scrap_return_form_url text,
  ADD COLUMN IF NOT EXISTS spare_parts_collected boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS files_updated boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS correction_notes text,
  ADD COLUMN IF NOT EXISTS supplier_invoice_url text,
  ADD COLUMN IF NOT EXISTS supplier_report_url text;
