
ALTER TABLE public.accident_claims
  ADD COLUMN IF NOT EXISTS covered_by_policy boolean,
  ADD COLUMN IF NOT EXISTS policy_analysis_notes text,
  ADD COLUMN IF NOT EXISTS quotations_requested_at timestamptz,
  ADD COLUMN IF NOT EXISTS quotation_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS selected_supplier_garage text,
  ADD COLUMN IF NOT EXISTS selected_supplier_contact text,
  ADD COLUMN IF NOT EXISTS quotation_amount numeric,
  ADD COLUMN IF NOT EXISTS quotation_selected_at timestamptz,
  ADD COLUMN IF NOT EXISTS work_order_number text,
  ADD COLUMN IF NOT EXISTS work_order_url text,
  ADD COLUMN IF NOT EXISTS work_order_approved_at timestamptz,
  ADD COLUMN IF NOT EXISTS vehicle_handover_at timestamptz,
  ADD COLUMN IF NOT EXISTS repair_status text DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS repair_completion_reported_at timestamptz,
  ADD COLUMN IF NOT EXISTS payment_requested_by_garage_at timestamptz,
  ADD COLUMN IF NOT EXISTS maintenance_per_wo_ok boolean,
  ADD COLUMN IF NOT EXISTS vehicle_returned_at timestamptz,
  ADD COLUMN IF NOT EXISTS payment_receipt_url text,
  ADD COLUMN IF NOT EXISTS receipt_signed_at timestamptz,
  ADD COLUMN IF NOT EXISTS salvage_collected boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS salvage_value numeric,
  ADD COLUMN IF NOT EXISTS salvage_notes text,
  ADD COLUMN IF NOT EXISTS salvage_collected_at timestamptz,
  ADD COLUMN IF NOT EXISTS compensation_requested_at timestamptz,
  ADD COLUMN IF NOT EXISTS third_party_agreed boolean,
  ADD COLUMN IF NOT EXISTS agreed_amount numeric,
  ADD COLUMN IF NOT EXISTS collected_from_third_party numeric,
  ADD COLUMN IF NOT EXISTS collected_at timestamptz,
  ADD COLUMN IF NOT EXISTS legal_case_number text,
  ADD COLUMN IF NOT EXISTS legal_filed_at timestamptz,
  ADD COLUMN IF NOT EXISTS legal_status text,
  ADD COLUMN IF NOT EXISTS legal_outcome text,
  ADD COLUMN IF NOT EXISTS legal_outcome_at timestamptz,
  ADD COLUMN IF NOT EXISTS pro_forma_invoice_url text,
  ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS archived_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_accident_claims_workflow_stage ON public.accident_claims(workflow_stage);
CREATE INDEX IF NOT EXISTS idx_accident_claims_fault_party ON public.accident_claims(fault_party);
